# Site
name: "Memoirs"
title: "Memoirs"
description: "I will take you on the fabulous world of exploration. Travel, culture, lifestyle. Eat, Pray, Love!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
disqus: 'demowebsite'
include: ["_pages"]
permalink: /:year-:month-:day/:title/
email: qyc027@outlook.com

# Authors
authors:
  ivan_chien:
    name: Ivan Chien
    display_name: qyc
    avatar: 'assets/images/avatar-sal.png'
    email: qyc027@outlook.com
    web: https://yescafe.github.io/
    description: "简简单单的路人角色"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
