# Site
name: "LAB530"
title: "LAB530 page"
description: ""
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl:
disqus: 'demowebsite'
include: ["_pages"]
permalink: /:year-:month-:day/:title/
email: qyc027@outlook.com

# Bulletin
bulletin:
  - 仓库链接：<a href="https://github.com/lab530/lab530.github.io">https://github.com/lab530/lab530.github.io</a>
  - QQ 群号：613998612

# CDN prefix
CDN_prefix: https://cdn.jsdelivr.net/gh/lab530/assets_images_storage/
CDN_gallery_prefix: https://cdn.jsdelivr.net/gh/lab530/pages-gallery-storage/

# Authors
authors:
  ivan_chien:
    name: Ivan Chien
    display_name: qyc
    avatar: 'assets/images/avatars/ivan_chien.png'
    github: yescafe
    email: qyc027@outlook.com
    web: https://yescafe.github.io/
    description: "简简单单的路人角色"
  lazarus:
    name: lazarus
    display_name: lazarus
    avatar: 'assets/images/avatars/lazarus.jpg'
    github: Lazarus-glhf
    email: redrumlivedog@outlook.com
    web: https://lazarus-glhf.github.io/
    description: "努力的生活。"
  dengyue:
    name: dengyue
    display_name: wdf
    avatar: 'assets/images/avatars/dengyue.jpg'
    github: dengyueW
    email: dengyue1102@163.com
    web: https://dengyuew.github.io/
    description: "好好学习"
  Ereflect:
    name: Ereflect
    display_name: Ereflect
    avatar: 'assets/images/avatars/Ereflect.jpg'
    github: ErefIect
    email: luodan_0464@qq.com
    web: 
    description: ""
  PlumYu:
    name: PlumYu
    display_name: Li Yu
    avatar: 'assets/images/avatars/PlumYu.jpeg'
    github: PlumYu
    email: 2477934060@qq.com
    web: 
    description: ""
  Hanpro:
    name: Hanpro
    display_name: wzh
    avatar: 'assets/images/avatars/hanpro.jpeg'
    github: Hanpro9
    email: 1422306220@qq.com
    description: "记得对自己热爱的专业保持激情"
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, readme.md, Gemfile, Gemfile.lock]

components:
  busuanzi:
    enabled: true
    start_date: 2022-10-28